#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/springdemo?serverTimezone=GMT%2B8
#  username: root
#  password: 123456
#  user:
#   name: jack
#   age: 21
#   language:
#     - java
#     - php
#     - ios

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

server:
  port: 8088
#  servlet:
logging:
  level:
    cn.itcast: debug
#    org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun6?serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
  # mapper-locations: mapper/*.xml
  type-aliases-package: cn.itcast.pojo
